name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

env:
  REGISTRY: docker.io
  IMAGE_NAMESPACE: mariodotdev

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ===== Docker =====
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Go Service
        uses: docker/build-push-action@v5
        with:
          context: services/go-service
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/go-service:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/go-service:${{ github.sha }}

      - name: Build & Push Node Service
        uses: docker/build-push-action@v5
        with:
          context: services/node-service
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/node-service:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/node-service:${{ github.sha }}

      # ===== Kubernetes =====
      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/
          kubectl rollout status deployment/go-service
          kubectl rollout status deployment/node-service
